indicateurs_delai_homepage:
      path:   /delai
      defaults: { _controller: IndicateursBundle:Delai:index }

indicateurs_delai_traitement_table:
      path:   /delai/traitement/table
      defaults: { _controller: IndicateursBundle:DelaiTraitement:Table }
      requirements:
          method:  GET

indicateurs_delai_traitement_graph:
      path:   /delai/traitement/graph
      defaults: { _controller: IndicateursBundle:DelaiTraitement:Graph }
      requirements:
          method:  GET

indicateurs_delai_reponse_table:
      path:   /delai/reponse/table
      defaults: { _controller: IndicateursBundle:DelaiReponse:Table }
      requirements:
          method:  GET

indicateurs_delai_reponse_graph:
      path:   /delai/reponse/graph
      defaults: { _controller: IndicateursBundle:DelaiReponse:Graph }
      requirements:
          method:  GET

indicateurs_delai_traitement_incident_contrat:
      path:   /delai/traitement/incident/contrat
      defaults: { _controller: IndicateursBundle:Contractuel:IncidentDelaiTraitementContrat }
      requirements:
          method:  GET

indicateurs_delai_traitement_support_contrat:
      path:   /delai/traitement/support/contrat
      defaults: { _controller: IndicateursBundle:DelaiTmntSupport:DelaiTtmntSupport }
      requirements:
          method:  GET
