indicateurs_evolutionNBTicket_homepage:
      path:   /evolutionnbticket
      defaults: { _controller: IndicateursBundle:EvolutionNbTicket:index}

indicateurs_evolutionNBTicket_graph:
      path:   /evolutionnbticket/graph
      defaults: { _controller: IndicateursBundle:EvolutionNbTicket:Graph}
      requirements:
          method:  GET

indicateurs_evolutionNBTicket_table:
      path:   /evolutionnbticket/table
      defaults: { _controller: IndicateursBundle:EvolutionNbTicket:Table}
      requirements:
          method:  GET