indicateurs_openclose_homepage:
    path:     /openclose
    defaults: { _controller: IndicateursBundle:OpenClose:index }

indicateurs_openclose_graph:
    path:     /openclose/graph
    defaults: { _controller: IndicateursBundle:OpenClose:Graph}
    requirements:
        method:  GET

indicateurs_openclose_table:
    path:     /openclose/table
    defaults: { _controller: IndicateursBundle:OpenClose:Table}
    requirements:
        method:  GET