indicateurs_contrat_reouverture_incident_homepage:
      path:   /contrat
      defaults: { _controller: IndicateursBundle:Contractuel:index }

indicateurs_contrat_reouverture_incident_count:
      path:   /contrat/reoinci/count
      defaults: { _controller: IndicateursBundle:Contractuel:IncidentReouvertureCount }
      requirements:
          method:  GET
          year:  \d+

indicateurs_contrat_reouverture_incident_table:
      path:   /contrat/reoinci/table
      defaults: { _controller: IndicateursBundle:Contractuel:IncidentReouvertureTable }
      requirements:
          method:  GET
          year:  \d+