indicateurs_reouverture_homepage:
    path:   /reopen
    defaults: { _controller: IndicateursBundle:Reouverture:index }

indicateurs_reouverture_table:
    path:   /reopen/table
    defaults: { _controller: IndicateursBundle:Reouverture:Table }
    requirements:
        method:  GET

indicateurs_reouverture_graph:
    path:   /reopen/graph
    defaults: { _controller: IndicateursBundle:Reouverture:Graph}
    requirements:
        method:  GET
