indicateurs_homepage:
    path:     /
    defaults: { _controller: IndicateursBundle:Default:index }

indicateurs_openclose:
    resource: "@IndicateursBundle/Resources/config/openclose_routing.yml"

indicateurs_reouverture:
    resource: "@IndicateursBundle/Resources/config/reouverture_routing.yml"

indicateurs_delai:
    resource: "@IndicateursBundle/Resources/config/delai_routing.yml"

indicateurs_contrat_reouverture_incident:
    resource: "@IndicateursBundle/Resources/config/reouverture_incident_routing.yml"

indicateurs_supanoforfait_count:
    path:   /supanoforfait/count
    defaults: { _controller: IndicateursBundle:SupAnoForfait:getCountSupAnoForfait}
    requirements:
        method:  GET
        year:  \d+

indicateurs_evolutionNBTicket:
    resource: "@IndicateursBundle/Resources/config/evolutionNbTicket_routing.yml"

inicateurs_contractuel:
    resource: "@IndicateursBundle/Resources/config/contracuel_routing.yml"

indicateurs_help:
    path:   /help
    defaults: { _controller: IndicateursBundle:Help:index}
    requirements:
        method:  GET
