indicateurs_homepage:
    path:     /
    defaults: { _controller: IndicateursBundle:Default:index }

indicateurs_openclose:
    resource: "@IndicateursBundle/Resources/config/openclose_routing.yml"

indicateurs_reouverture:
    resource: "@IndicateursBundle/Resources/config/reouverture_routing.yml"

indicateurs_delai_traitement:
    resource: "@IndicateursBundle/Resources/config/delai_traitement_routing.yml"

indicateurs_contrat_reouverture_incident:
    resource: "@IndicateursBundle/Resources/config/reouverture_incident_routing.yml"

indicateurs_supanoforfait_count:
      path:   /supanoforfait/count/{year}
      defaults: { _controller: IndicateursBundle:SupAnoForfait:getCountSupAnoForfait}
      requirements:
          method:  GET
          year:  \d+
