indicateurs_homepage:
    path:     /
    defaults: { _controller: IndicateursBundle:Default:index }

indicateurs_openclose_homepage:
    path:     /openclose
    defaults: { _controller: IndicateursBundle:OpenClose:index }

indicateurs_openclose_graph:
    path:     /openclose/graph/{year}/{project}
    defaults: { _controller: IndicateursBundle:OpenClose:Graph,project: -1 }
    requirements:
        method:  GET
        year:  \d+

indicateurs_openclose_table:
    path:     /openclose/table/{year}/{project}
    defaults: { _controller: IndicateursBundle:OpenClose:Table,project: -1 }
    requirements:
        method:  GET
        year:  \d+

indicateurs_reouverture_homepage:
    path:   /reopen
    defaults: { _controller: IndicateursBundle:Reouverture:index }

indicateurs_reouverture_table:
    path:   /reopen/table/{year}/{project}
    defaults: { _controller: IndicateursBundle:Reouverture:Table,project: -1 }
    requirements:
        method:  GET
        year:  \d+

indicateurs_reouverture_graph:
    path:   /reopen/graph/{year}/{project}
    defaults: { _controller: IndicateursBundle:Reouverture:Graph,project: -1 }
    requirements:
        method:  GET
        year:  \d+