homepage:
    path:     /
    defaults: { _controller: ProjectBundle:HPGlobale:index }

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /projet

gantt:
    resource: "@GanttBundle/Controller/"
    type:     annotation
    prefix:   /gantt

indicateurs:
    resource: "@IndicateursBundle/Resources/config/routing.yml"
    prefix:   /indic
