fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

project_environnement:
    resource: "@ProjectBundle/Controller/EnvironnementController.php"
    type:     annotation

project_project:
    resource: "@ProjectBundle/Controller/ProjectController.php"
    type:     annotation

homepage:
    path:     /
    defaults: { _controller: ProjectBundle:HPGlobale:index }

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /projet

gantt:
    resource: "@GanttBundle/Controller/"
    type:     annotation
    prefix:   /gantt

indicateurs:
    resource: "@IndicateursBundle/Resources/config/routing.yml"
    prefix:   /indic
