<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityCommentRepository extends EntityRepository
{
    /**
     * Retourne la liste des commentaires des activités
     *
     * @param $id_activity
     * @return array
     */
    public function getActivityComments($id_activity){

        $query      = $this->createQueryBuilder('ac');
        $query->select('ac.id id, ac.libelle, ac.auteur, DATE_FORMAT(ac.dateCreation,\'%d/%m/%Y %H:%i\') as dateCreation')
            ->leftJoin("ac.activity",'a')
            ->where('a.id = :idactivity' )
            ->orderBy('ac.dateCreation', 'DESC')
            ->setParameter('idactivity',$id_activity);

        return $query->getQuery()->getArrayResult();
    }
}
