<?php

namespace ProjectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    /**
     * Permet de selectionner les contacts.
     *
     * @param $idBnp
     * @param $name
     * @param $prenom
     * @param $mail
     * @param $idJtrac
     * @param $project
     * @return array
     */
    public function getContacts($name,$prenom,$mail,$idJtrac,$idBnp,$project){

        $query      = $this->createQueryBuilder('c');
        $query->select('p.name project, c.id DT_RowId, c.name, c.prenom, c.description, c.idBnp, c.idJtrac, c.mail')
            ->leftJoin("c.project",'p')
            ->orderBy('c.nom', 'ASC')
            ->orderBy('c.prenom', 'ASC');

        if($idBnp !=-1 && $idBnp != 'all' && $idBnp != Null){
            $query->andWhere('c.idBnp = :idBnp')
                ->setParameter('idBnp',$idBnp);
        }
        if($name !=-1 && $name != 'all' && $name != Null){
            $query->andWhere('c.name = :name')
                ->setParameter('name',$name);
        }
        if($prenom !=-1 && $prenom != 'all' && $prenom != Null){
            $query->andWhere('c.prenom = :prenom')
                ->setParameter('prenom',$prenom);
        }
        if($mail !=-1 && $mail != 'all' && $mail != Null){
            $query->andWhere('c.mail = :mail')
                ->setParameter('mail',$mail);
        }
        if($idJtrac !=-1 && $idJtrac != 'all' && $idJtrac != Null){
            $query->andWhere('p.idJtrac = :idJtrac')
                ->setParameter('idJtrac',$idJtrac);
        }
        if($project !=-1 && $project != 'all' && $project != Null){
            $query->andWhere('p.projectId = :project')
                ->setParameter('project',$project);
        }

        return $query->getQuery()->getArrayResult();
    }
}
