<?php

namespace GanttBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Gantt_assigsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Gantt_assigsRepository extends EntityRepository
{
}
