project_contact_homepage:
  path: /contact
  defaults: { _controller: ProjectBundle:Contact:index}

project_contact_table:
    path:     /contact/table
    defaults: { _controller: ProjectBundle:Contact:Table}
    requirements:
        method:  GET