<?php

namespace IndicateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Indic_TRSBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Indic_TRSBRepository extends EntityRepository
{
    /**
     * Retourne l'info trsb pour l'item
     *
     * @param $itemId
     * @return mixed
     */
    public function getTRSBByItemId($itemId)
    {
        $query = $this->createQueryBuilder('t');
        $query->select('t')
            ->where('t.Indic_items = :itemId')
            ->setParameter('itemId', $itemId);

        return $query->getQuery()->getOneOrNullResult();
    }
}
