<?php

namespace IndicateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Indic_historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Indic_historyRepository extends EntityRepository
{
    /**
     * Recherche un Item avec son JtracId
     *
     * @param $historyId
     * @return mixed
     */
    public function getHistoryByHistoryId($historyId)
    {
        $query = $this->createQueryBuilder('h');
        $query->select('h')
            ->where('h.historyId = :historyId')
            ->setParameter('historyId', $historyId);

        return $query->getQuery()->getOneOrNullResult();
    }
}
