<?php

namespace IndicateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Indic_itemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Indic_itemsRepository extends EntityRepository
{
    /**
     * Recherche un Item avec son JtracId
     *
     * @param $itemId
     * @return mixed
     */
    public function getItemByItemId($itemId)
    {
        $query = $this->createQueryBuilder('i');
        //$query->select('i.itemId');
        $query->where('i.itemId = :itemId')
            ->setParameter('itemId', $itemId);

        return $query->getQuery()->getOneOrNullResult();
    }

}
